name: fyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_image_slideshow: ^0.1.6

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.2

  image_picker: ^1.1.2
  camera: ^0.11.2+1
  http: ^1.2.0
  mobile_scanner: ^5.1.1
  google_mlkit_image_labeling: ^0.13.0
  google_mlkit_text_recognition: ^0.14.0

  speech_to_text: ^7.0.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.1
  intl_phone_field: ^3.2.0
  intl: ^0.20.2

  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/vocamart_icon.png"
