// How this file works:
// 1) Data/models are declared first (if any).
// 2) UI widgets are built in build() methods.
// 3) Helper methods are used to keep UI code clean.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:fyp/User/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuVFCQ4xO4i4iDx6SbgRaklxzslnVhhlo',
    appId: '1:630951250062:web:ce21f984839628b6a0e1df',
    messagingSenderId: '630951250062',
    projectId: 'fyp2-90049',
    authDomain: 'fyp2-90049.firebaseapp.com',
    storageBucket: 'fyp2-90049.firebasestorage.app',
    measurementId: 'G-PJ27Q8MLQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lQtM9-AC2nevhxT2PRpzQ3PSNu9RZok',
    appId: '1:630951250062:android:d3068952eee31973a0e1df',
    messagingSenderId: '630951250062',
    projectId: 'fyp2-90049',
    storageBucket: 'fyp2-90049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBuTgKWB2N727BTPV5IxYeWsTXVDIonW4',
    appId: '1:630951250062:ios:8c4dcb9ce6fa37d1a0e1df',
    messagingSenderId: '630951250062',
    projectId: 'fyp2-90049',
    storageBucket: 'fyp2-90049.firebasestorage.app',
    iosBundleId: 'tarumt.edu.my.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBuTgKWB2N727BTPV5IxYeWsTXVDIonW4',
    appId: '1:630951250062:ios:8c4dcb9ce6fa37d1a0e1df',
    messagingSenderId: '630951250062',
    projectId: 'fyp2-90049',
    storageBucket: 'fyp2-90049.firebasestorage.app',
    iosBundleId: 'tarumt.edu.my.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuVFCQ4xO4i4iDx6SbgRaklxzslnVhhlo',
    appId: '1:630951250062:web:b73ae9e4bb98cb73a0e1df',
    messagingSenderId: '630951250062',
    projectId: 'fyp2-90049',
    authDomain: 'fyp2-90049.firebaseapp.com',
    storageBucket: 'fyp2-90049.firebasestorage.app',
    measurementId: 'G-4N2BP6D9M5',
  );
}


